from datetime import datetime
from typing import Protocol

from domain.entities import Record


class Repo(Protocol):
    async def add(self, data: Record) -> int | None: ...
    async def get(self) -> Record | None: ...
    async def get_list(self) -> list[Record]: ...
    async def add_list(self, data: list[Record]) -> None: ...
    async def get_by_name(self, name: str) -> list[Record]: ...


class Clock(Protocol):
    def now(self) -> datetime: ...